oauth:
  clientId: <clientId>
  clientSecret: <clientSecret>
  checkTokenUrl: https://www.googleapis.com/oauth2/v3/tokeninfo?access_token={accessToken}
  userInfoUrl: https://www.googleapis.com/plus/v1/people/me
